---
title: "Data For Visualization"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(zoo)
```

## Clean the Data

```{r import data}
history_df = read.csv('historic.csv')

year_to_date_df = read.csv('year_to_date.csv') %>% 
  rename(Lon_Lat = New.Georeferenced.Column)
```

```{r data cleaning}
Shooting_df = bind_rows(history_df, year_to_date_df) %>% 
  janitor::clean_names() %>% 
  separate(occur_date, c("month","day","year")) %>% 
  separate(occur_time, c("hour","minute","second")) %>% 
  mutate(
    year = as.numeric(year), 
    month = as.numeric(month),
    day = as.numeric(day),
    hour = as.numeric(hour),
    minute = as.numeric(minute)
    ) %>% 
  select(-second)

```

## race_sex_vicdf

```{r race_sex_vicdf}
race_sex_vicdf = Shooting_df %>%
  subset(vic_sex == "M" | vic_sex == "F") %>% 
  group_by(vic_sex,vic_race) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = vic_sex, values_from = count) %>% 
  subset(vic_race != 'UNKNOWN')

```

## race_sex_perpdf
```{r race_sex_perpdf}
race_sex_perpdf = Shooting_df %>%
  subset(perp_sex == "M" | perp_sex == "F") %>% 
  group_by(perp_sex,perp_race) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = perp_sex, values_from = count) %>% 
  subset(perp_race != 'UNKNOWN')
```

## boro_df

```{r boro_df}
boro_df = Shooting_df %>%
  group_by(boro) %>% 
  summarise(count = n())
```


## location_df

```{r location_df}
location_df = Shooting_df %>%
  mutate_all(list(~na_if(.,""))) %>%
  drop_na(location_desc) %>% 
  group_by(location_desc) %>% 
  summarise(count = n()) %>% 
  subset(count >= 10)
```


## year_trend_df_2020

```{r}
year_trend_df_2020 = Shooting_df %>%
  group_by(year, boro) %>%
  mutate(
    boro = factor(boro)
  ) %>% 
  summarise(count = n()) %>% 
  subset(year != '2021')
  
```

